services:
  - type: web
    name: line-translator
    env: python
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    branch: main
